---
title: "ESM 232 Assignment 3"
format: html
author: "Ella Moore and Sneha Kumar"
---

Read the climate data from the txt file into a data table 
```{r}
library(here)
library(dplyr)
clim_data<-read.table(here("Assignments/clim.txt"), header = T)
```
Clean the climate data into two new data frames 
The first includes only the average minimum temperature (C) for the month of February 
The second contains the average precipitation (mm) for the month of January
```{r}
#Calculate the annual average minimum temp in Feb 
feb_min_temp <- clim_data |>
  filter(month == "2") |>
  select(day, month, year, tmin_c)
feb_min_temp

avg_min_temp <- feb_min_temp |>
  group_by(year) |>
  summarize(avg_temp = mean(tmin_c, na.rm = TRUE))
avg_min_temp

#Calculate the annual average precipitation in Jan 
jan_av_precipitation <- clim_data |>
  filter(month == "1") |>
  select(day, month, year, precip)
jan_av_precipitation

avg_precip <- jan_av_precipitation |>
  group_by(year) |>
  summarize(avg_precip = mean(precip, na.rm = TRUE))
avg_precip

# Call the function located in the R folder
source(here("R/HW3.R"))

# Merge the data frames into one and create new blank column
inputs <- merge(avg_min_temp, avg_precip, by="year") |>
  mutate(yield = yield_anomaly(avg_temp,avg_precip))

inputs
```

```{r}
#Create a summary Table for the yield anomaly min, max, and mean
mean(inputs$yield)
max(inputs$yield)
min(inputs$yield)
```

